version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "8001:8001"
        depends_on:
            - "php"
        volumes:
            - "$PWD/nginx/conf:/etc/nginx/conf.d"
            - "$PWD/wwwlogs:/var/log/nginx"
            - "$PWD/wwwroot:/var/www/html"
        networks:
            - develop
        container_name: "compose-nginx"
    php:
        build: ./php
        ports:
            - "9000:9000"
        volumes:
            - "$PWD/wwwroot:/var/www/html"
        networks:
            - develop
        container_name: "compose-php"
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - "$PWD/mysql:/var/lib/mysql"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
            develop:
                ipv4_address: 10.10.10.1
        container_name: "compose-mysql"
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - develop
        container_name: "compose-redis"
networks:
    develop:
        driver: bridge
        ipam:
            config:
                - subnet: 10.10.0.0/16
